// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/overview": {
    params: {};
  };
  "/contacts": {
    params: {};
  };
  "/contacts/new": {
    params: {};
  };
  "/contacts/imports": {
    params: {};
  };
  "/contacts/:id": {
    params: {
      "id": string;
    };
  };
  "/contacts/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/contact-lists": {
    params: {};
  };
  "/contact-lists/new": {
    params: {};
  };
  "/contact-lists/:id": {
    params: {
      "id": string;
    };
  };
  "/contact-lists/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/waiting-lists": {
    params: {};
  };
  "/waiting-lists/new": {
    params: {};
  };
  "/waiting-lists/:id": {
    params: {
      "id": string;
    };
  };
  "/waiting-lists/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/contact-interactions": {
    params: {};
  };
  "/contact-interactions/new": {
    params: {};
  };
  "/contact-interactions/:id": {
    params: {
      "id": string;
    };
  };
  "/contact-interactions/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/logout": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/overview" | "/contacts" | "/contacts/new" | "/contacts/imports" | "/contacts/:id" | "/contacts/:id/edit" | "/contact-lists" | "/contact-lists/new" | "/contact-lists/:id" | "/contact-lists/:id/edit" | "/waiting-lists" | "/waiting-lists/new" | "/waiting-lists/:id" | "/waiting-lists/:id/edit" | "/contact-interactions" | "/contact-interactions/new" | "/contact-interactions/:id" | "/contact-interactions/:id/edit" | "/logout" | "/*";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "layouts/private.layout.tsx": {
    id: "layouts/private.layout";
    page: "/overview" | "/contacts" | "/contacts/new" | "/contacts/imports" | "/contacts/:id" | "/contacts/:id/edit" | "/contact-lists" | "/contact-lists/new" | "/contact-lists/:id" | "/contact-lists/:id/edit" | "/waiting-lists" | "/waiting-lists/new" | "/waiting-lists/:id" | "/waiting-lists/:id/edit" | "/contact-interactions" | "/contact-interactions/new" | "/contact-interactions/:id" | "/contact-interactions/:id/edit";
  };
  "routes/main/overview/layout.tsx": {
    id: "routes/main/overview/layout";
    page: "/overview";
  };
  "routes/main/overview/index.tsx": {
    id: "routes/main/overview/index";
    page: "/overview";
  };
  "routes/main/contacts/layout.tsx": {
    id: "routes/main/contacts/layout";
    page: "/contacts" | "/contacts/new" | "/contacts/imports" | "/contacts/:id" | "/contacts/:id/edit";
  };
  "routes/main/contacts/index.tsx": {
    id: "routes/main/contacts/index";
    page: "/contacts";
  };
  "routes/main/contacts/new.tsx": {
    id: "routes/main/contacts/new";
    page: "/contacts/new";
  };
  "routes/main/contacts/imports.tsx": {
    id: "routes/main/contacts/imports";
    page: "/contacts/imports";
  };
  "routes/main/contacts/detail.tsx": {
    id: "routes/main/contacts/detail";
    page: "/contacts/:id";
  };
  "routes/main/contacts/edit.tsx": {
    id: "routes/main/contacts/edit";
    page: "/contacts/:id/edit";
  };
  "routes/main/contact-lists/layout.tsx": {
    id: "routes/main/contact-lists/layout";
    page: "/contact-lists" | "/contact-lists/new" | "/contact-lists/:id" | "/contact-lists/:id/edit";
  };
  "routes/main/contact-lists/index.tsx": {
    id: "routes/main/contact-lists/index";
    page: "/contact-lists";
  };
  "routes/main/contact-lists/new.tsx": {
    id: "routes/main/contact-lists/new";
    page: "/contact-lists/new";
  };
  "routes/main/contact-lists/detail.tsx": {
    id: "routes/main/contact-lists/detail";
    page: "/contact-lists/:id";
  };
  "routes/main/contact-lists/edit.tsx": {
    id: "routes/main/contact-lists/edit";
    page: "/contact-lists/:id/edit";
  };
  "routes/main/waiting-lists/layout.tsx": {
    id: "routes/main/waiting-lists/layout";
    page: "/waiting-lists" | "/waiting-lists/new" | "/waiting-lists/:id" | "/waiting-lists/:id/edit";
  };
  "routes/main/waiting-lists/index.tsx": {
    id: "routes/main/waiting-lists/index";
    page: "/waiting-lists";
  };
  "routes/main/waiting-lists/new.tsx": {
    id: "routes/main/waiting-lists/new";
    page: "/waiting-lists/new";
  };
  "routes/main/waiting-lists/detail.tsx": {
    id: "routes/main/waiting-lists/detail";
    page: "/waiting-lists/:id";
  };
  "routes/main/waiting-lists/edit.tsx": {
    id: "routes/main/waiting-lists/edit";
    page: "/waiting-lists/:id/edit";
  };
  "routes/main/contact-interactions/layout.tsx": {
    id: "routes/main/contact-interactions/layout";
    page: "/contact-interactions" | "/contact-interactions/new" | "/contact-interactions/:id" | "/contact-interactions/:id/edit";
  };
  "routes/main/contact-interactions/index.tsx": {
    id: "routes/main/contact-interactions/index";
    page: "/contact-interactions";
  };
  "routes/main/contact-interactions/new.tsx": {
    id: "routes/main/contact-interactions/new";
    page: "/contact-interactions/new";
  };
  "routes/main/contact-interactions/detail.tsx": {
    id: "routes/main/contact-interactions/detail";
    page: "/contact-interactions/:id";
  };
  "routes/main/contact-interactions/edit.tsx": {
    id: "routes/main/contact-interactions/edit";
    page: "/contact-interactions/:id/edit";
  };
  "routes/logout.tsx": {
    id: "logout";
    page: "/logout";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "layouts/private.layout": typeof import("./app/layouts/private.layout.tsx");
  "routes/main/overview/layout": typeof import("./app/routes/main/overview/layout.tsx");
  "routes/main/overview/index": typeof import("./app/routes/main/overview/index.tsx");
  "routes/main/contacts/layout": typeof import("./app/routes/main/contacts/layout.tsx");
  "routes/main/contacts/index": typeof import("./app/routes/main/contacts/index.tsx");
  "routes/main/contacts/new": typeof import("./app/routes/main/contacts/new.tsx");
  "routes/main/contacts/imports": typeof import("./app/routes/main/contacts/imports.tsx");
  "routes/main/contacts/detail": typeof import("./app/routes/main/contacts/detail.tsx");
  "routes/main/contacts/edit": typeof import("./app/routes/main/contacts/edit.tsx");
  "routes/main/contact-lists/layout": typeof import("./app/routes/main/contact-lists/layout.tsx");
  "routes/main/contact-lists/index": typeof import("./app/routes/main/contact-lists/index.tsx");
  "routes/main/contact-lists/new": typeof import("./app/routes/main/contact-lists/new.tsx");
  "routes/main/contact-lists/detail": typeof import("./app/routes/main/contact-lists/detail.tsx");
  "routes/main/contact-lists/edit": typeof import("./app/routes/main/contact-lists/edit.tsx");
  "routes/main/waiting-lists/layout": typeof import("./app/routes/main/waiting-lists/layout.tsx");
  "routes/main/waiting-lists/index": typeof import("./app/routes/main/waiting-lists/index.tsx");
  "routes/main/waiting-lists/new": typeof import("./app/routes/main/waiting-lists/new.tsx");
  "routes/main/waiting-lists/detail": typeof import("./app/routes/main/waiting-lists/detail.tsx");
  "routes/main/waiting-lists/edit": typeof import("./app/routes/main/waiting-lists/edit.tsx");
  "routes/main/contact-interactions/layout": typeof import("./app/routes/main/contact-interactions/layout.tsx");
  "routes/main/contact-interactions/index": typeof import("./app/routes/main/contact-interactions/index.tsx");
  "routes/main/contact-interactions/new": typeof import("./app/routes/main/contact-interactions/new.tsx");
  "routes/main/contact-interactions/detail": typeof import("./app/routes/main/contact-interactions/detail.tsx");
  "routes/main/contact-interactions/edit": typeof import("./app/routes/main/contact-interactions/edit.tsx");
  "logout": typeof import("./app/routes/logout.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};