// Generated by React Router

import type { GetInfo, GetAnnotations } from 'react-router/internal'

type Module = typeof import('../edit.js')

type Info = GetInfo<{
  file: 'routes/main/contact-lists/edit.tsx'
  module: Module
}>

type Matches = [
  {
    id: 'root'
    module: typeof import('../../../../root.js')
  },
  {
    id: 'layouts/private.layout'
    module: typeof import('../../../../layouts/private.layout.js')
  },
  {
    id: 'routes/main/contact-lists/layout'
    module: typeof import('../layout.js')
  },
  {
    id: 'routes/main/contact-lists/edit'
    module: typeof import('../edit.js')
  },
]

type Annotations = GetAnnotations<Info & { module: Module; matches: Matches }, false>

export namespace Route {
  // links
  export type LinkDescriptors = Annotations['LinkDescriptors']
  export type LinksFunction = Annotations['LinksFunction']

  // meta
  export type MetaArgs = Annotations['MetaArgs']
  export type MetaDescriptors = Annotations['MetaDescriptors']
  export type MetaFunction = Annotations['MetaFunction']

  // headers
  export type HeadersArgs = Annotations['HeadersArgs']
  export type HeadersFunction = Annotations['HeadersFunction']

  // middleware
  export type MiddlewareFunction = Annotations['MiddlewareFunction']

  // clientMiddleware
  export type ClientMiddlewareFunction = Annotations['ClientMiddlewareFunction']

  // loader
  export type LoaderArgs = Annotations['LoaderArgs']

  // clientLoader
  export type ClientLoaderArgs = Annotations['ClientLoaderArgs']

  // action
  export type ActionArgs = Annotations['ActionArgs']

  // clientAction
  export type ClientActionArgs = Annotations['ClientActionArgs']

  // HydrateFallback
  export type HydrateFallbackProps = Annotations['HydrateFallbackProps']

  // Component
  export type ComponentProps = Annotations['ComponentProps']

  // ErrorBoundary
  export type ErrorBoundaryProps = Annotations['ErrorBoundaryProps']
}
